# Generated by Django 4.1.5 on 2023-01-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('Telefono', models.CharField(max_length=9, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Precio', models.CharField(max_length=20, verbose_name='Precio')),
                (Imagen==models.ImageField(upload_to="imagenes", null=True, verbose_name='Imagen')),
            ],
        ),

    ]
